/**
 * Diffs the TS port (src/prep) against golden JSON generated by the real
 * Python prep_portions.py on the same TIT fixture. Run with:
 *
 *   npm run verify:prep
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { runPrep } from "../src/prep/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const fixturesDir = join(here, "..", "src", "prep", "__fixtures__");

function read(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf-8");
}

const result = runPrep({
  book: "TIT",
  ultText: read("57-TIT-sample.usfm"),
  ultPath: "fixtures/prep_portions/57-TIT-sample.usfm",
  tn: { path: "fixtures/prep_portions/tn_TIT.tsv", text: read("tn_TIT.tsv") },
  tq: { path: "fixtures/prep_portions/tq_TIT.tsv", text: read("tq_TIT.tsv") },
  twl: { path: "fixtures/prep_portions/twl_TIT.tsv", text: read("twl_TIT.tsv") },
});

const golden = JSON.parse(read("golden-tit-prep.json")) as Record<string, unknown>;

// generated_at is a timestamp; everything else must match exactly.
delete (result as Record<string, unknown>).generated_at;
delete golden.generated_at;

// The port grew after the Python script was retired: each portion now also says whether the two texts cover it.
// Those fields are checked on their own and left out of the comparison with the old output, which must still match.
type Row = Record<string, unknown>;
const ADDED = ["tpl", "tps", "tpl_items", "tps_items"];
const counts = (result as { counts: Row }).counts;
const portions = (result as { chapters: { portions: Row[] }[] }).chapters.flatMap((chapter) => chapter.portions);
const problems: string[] = [];
for (const portion of portions) {
  if (portion.tpl !== 1) problems.push(`porción ${String(portion.ref)}: tpl debería ser 1`);
  if (portion.tps !== 0) problems.push(`porción ${String(portion.ref)}: sin UST, tps debería ser 0`);
  if (!Array.isArray(portion.tpl_items) || portion.tpl_items.length !== 1) problems.push(`porción ${String(portion.ref)}: falta su ítem de TPL`);
  if (!Array.isArray(portion.tps_items) || portion.tps_items.length !== 0) problems.push(`porción ${String(portion.ref)}: sin UST no hay ítem de TPS`);
}
if (counts.tpl !== portions.length || counts.tps !== 0) problems.push("los totales de tpl/tps no cuadran con las porciones");
if (problems.length) {
  console.error(["Campos de TPL/TPS:", ...problems].join("\n"));
  process.exit(1);
}
for (const row of [counts, ...portions]) for (const key of ADDED) delete row[key];

const resultText = JSON.stringify(result, null, 2);
const goldenText = JSON.stringify(golden, null, 2);

if (resultText === goldenText) {
  console.log("verify-prep: ok (matches the Python golden output; the TPL/TPS fields added since are consistent).");
  process.exit(0);
}

console.error("MISMATCH between TS port and Python golden output.\n");
const resultLines = resultText.split("\n");
const goldenLines = goldenText.split("\n");
const max = Math.max(resultLines.length, goldenLines.length);
let shown = 0;
for (let i = 0; i < max && shown < 40; i++) {
  if (resultLines[i] !== goldenLines[i]) {
    console.error(`line ${i + 1}:`);
    console.error(`  golden: ${goldenLines[i] ?? "<missing>"}`);
    console.error(`  ts:     ${resultLines[i] ?? "<missing>"}`);
    shown++;
  }
}
process.exit(1);
